import { useState } from "react";
import { FileBarChart2, Download, Trash2 } from "lucide-react";
import { PageHeader } from "../../../components/ui/Misc";
import Button from "../../../components/ui/Button";
import DataTable from "../../../components/ui/DataTable";
import { useReportList } from "../hooks/useReportList";
import GenerateReportDialog from "../components/GenerateReportDialog";
import { useAuth } from "../../../context/AuthContext";
import { PERMISSIONS } from "../../../constants/permissions";

const ReportsPage = () => {
  const { hasPermission } = useAuth();
  const canExport = hasPermission(PERMISSIONS.REPORT_EXPORT);
  const [dialogOpen, setDialogOpen] = useState(false);

  const {
    rows,
    pagination,
    loading,
    setPage,
    generating,
    create,
    remove,
    downloadCsv,
  } = useReportList();

  const columns = [
    { key: "title", label: "Report" },
    {
      key: "range",
      label: "Date range",
      className: "font-data whitespace-nowrap",
      render: (r) =>
        `${new Date(r.from).toLocaleDateString("en-IN")} – ${new Date(r.to).toLocaleDateString("en-IN")}`,
    },
    {
      key: "generatedBy",
      label: "Generated by",
      render: (r) => r.generatedBy?.name || "—",
    },
    {
      key: "totalRecords",
      label: "Datasets",
      className: "font-data",
      render: (r) => r.summary?.totalRecords ?? 0,
    },
    {
      key: "totalRows",
      label: "Rows",
      className: "font-data",
      render: (r) => r.summary?.totalRows ?? 0,
    },
    {
      key: "createdAt",
      label: "Generated",
      className: "font-data whitespace-nowrap",
      render: (r) => new Date(r.createdAt).toLocaleString(),
    },
    ...(canExport
      ? [
          {
            key: "actions",
            label: "",
            className: "text-right whitespace-nowrap",
            render: (r) => (
              <div className="flex items-center justify-end gap-1">
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    downloadCsv(r._id, r.title);
                  }}
                  aria-label={`Download ${r.title}`}
                  className="text-slate-300 hover:text-accent p-1 rounded-md hover:bg-accent-soft transition-colors"
                >
                  <Download size={14} />
                </button>
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    remove(r._id);
                  }}
                  aria-label={`Delete ${r.title}`}
                  className="text-slate-300 hover:text-danger p-1 rounded-md hover:bg-danger-soft transition-colors"
                >
                  <Trash2 size={14} />
                </button>
              </div>
            ),
          },
        ]
      : []),
  ];

  return (
    <div>
      <PageHeader
        title="Reports"
        subtitle={`${pagination.total} report${pagination.total === 1 ? "" : "s"}`}
        action={
          canExport && (
            <Button size="sm" onClick={() => setDialogOpen(true)}>
              <FileBarChart2 size={14} /> Generate report
            </Button>
          )
        }
      />

      <DataTable
        columns={columns}
        rows={rows}
        loading={loading}
        emptyTitle="No reports yet"
        emptyDescription={
          canExport
            ? "Generate a report to get a point-in-time snapshot you can download and share."
            : "Reports generated by your team will appear here."
        }
        emptyAction={
          canExport && (
            <Button size="sm" onClick={() => setDialogOpen(true)}>
              <FileBarChart2 size={14} /> Generate report
            </Button>
          )
        }
        page={pagination.page}
        pages={pagination.pages}
        onPageChange={setPage}
      />

      {canExport && (
        <GenerateReportDialog
          open={dialogOpen}
          onClose={() => setDialogOpen(false)}
          onGenerate={create}
          generating={generating}
        />
      )}
    </div>
  );
};

export default ReportsPage;
